Fix Chinese Translation for DME and Update some Translation
Nomi-CEu/Nomi-CEu pull request #575
Opened 2023-12-10 16:14 UTC by zero6six

I'm so sorry I put the translated language file for DME into the wrong folder by mistake, so I opened this PR to fix it.By the way, I updated translation for AE2, cns(CraftingNetherStar) and QB.

In the process of translation, I found some strange settings (or glitchs?) about `.displayName`:

1. Repeated <thermalexpansion:frame:64>.
https://github.com/Nomi-CEu/Nomi-CEu/blob/98ec44d31833ede7d8625bc2ed0116c30f57c88f/overrides/scripts/ThermalExpansion.zs#L390C1-L397

2. Only define the name of <cns:star_fragment>, ingnoring <cns:star_core>.
https://github.com/Nomi-CEu/Nomi-CEu/blob/98ec44d31833ede7d8625bc2ed0116c30f57c88f/overrides/scripts/extendedcrafting.zs#L281

I wonder if I could make a commit about changing these hardcoded strings to softcode strings?For example, `<thermalexpansion:frame:64>.displayName = "Thermal Machine Casing";` will be  replaced with`<thermalexpansion:frame:64>.displayName = (game.localize("thermal.machineframe"))`,and  I will add `thermal.machineframe=Thermal Machine Casing` to contenttweaker\lang\en_us.lang.

If you accept that, I will refactor all the hardcoded strings about item names next weekend.

2023-12-10 23:34 UTC, IntegerLimit commented
Note that CNS and some other mods will be replaced by Nomi Labs soon?

If you want to, go ahead! That would be very helpful. I am not sure of the timeline when I will have time to move everything to GroovyScript and Nomi-Labs, so you doing it will be very helpful.

*Instead of setting the display name in the scripts, find the original translation key for those items, and replace the value for those (both English and Chinese) in a lang file, in the relevant folder (or a new one), in the resources folder.*

That should probably go in a new Pull Request. I'll merge this first!

2023-12-10 23:36 UTC, IntegerLimit requested changes
Please resolve the two comments below.

2023-12-10 23:36 UTC, IntegerLimit commented on overrides/resources/appliedenergistics2/lang/zh_cn.lang
If this file is not needed, please delete it. Else, add it back (not sure if this is accidental)

2023-12-10 23:36 UTC, IntegerLimit commented on overrides/resources/cns/lang/zh_cn.lang
Is CNS the actual modid? Can you find the proper mod id for it?

2023-12-11 14:58 UTC, zero6six commented on overrides/resources/cns/lang/zh_cn.lang
Yes, the following is the mcmod.info information in "CraftingNetherStar 1.12.1 -1.1.jar".
```json
[
{
  "modid": "cns",
  "name": "Crafting Nether Star",
  "description": "Makes nether stars craftable. // Hace que las estrellas del Nether sean crafteables",
  "version": "1.1",
  "mcversion": "1.12.1",
  "url": "https://minecraft.curseforge.com/projects/craftingnetherstar",
  "updateUrl": "",
  "authorList": ["ZeckG"],
  "credits": "Carlos Bravo",
  "logoFile": "cns.png",
  "screenshots": [],
  "dependencies": []
}
]
```

2023-12-12 01:02 UTC, IntegerLimit approved these changes

2023-12-12 01:06 UTC, merged