Fix Chinese Translations and Softcode Item Names
Nomi-CEu/Nomi-CEu pull request #582
Opened 2023-12-16 19:21 UTC by zero6six

I divided this submission into two commits. The submission content is as shown in the commit information.

During the process of making my second commit, I encountered some naming variations that caught my attention. For instance, I noticed changes like Fueling Station being renamed to Fueling Station with a capital 'S', Dark Helm to Dark Steel Helmet, Ender Star to Endest Star, and Thorium-232 to Prepared Thorium-232.

While I understand the intent to maintain consistency and clarity in item names, I am curious about the rationale behind these specific changes. From my perspective, the original and new names seem quite similar in essence.

Anyway, I changed all the hard-coded item names to soft-coded ones according to the original text. I would appreciate any insights or guidelines you may have regarding the naming conventions. Your feedback will help me align my contributions more closely with the project's standards.

Thank you for your time and consideration.

2023-12-20 23:36 UTC, IntegerLimit commented
> I divided this submission into two commits. The submission content is as shown in the commit information.
> 
> During the process of making my second commit, I encountered some naming variations that caught my attention. For instance, I noticed changes like Fueling Station being renamed to Fueling Station with a capital 'S', Dark Helm to Dark Steel Helmet, Ender Star to Endest Star, and Thorium-232 to Prepared Thorium-232.
> 
> While I understand the intent to maintain consistency and clarity in item names, I am curious about the rationale behind these specific changes. From my perspective, the original and new names seem quite similar in essence.
> 
> Anyway, I changed all the hard-coded item names to soft-coded ones according to the original text. I would appreciate any insights or guidelines you may have regarding the naming conventions. Your feedback will help me align my contributions more closely with the project's standards.
> 
> Thank you for your time and consideration.

Sorry about the delay, this absolutely flew past me.

About the item names clarity:
- Most of the changes are just to reflect the material they are made out of in this modpack, rather than their initial material. This is meant to reduce confusion. (That is the case for most of the changes)
- I support the usage of capital letters at the start of each word, although it is not mandatory.
- It is also nice to have the words be spelt in an 'international' way, rather than the 'us' way (although this is usually not a problem).

Yeah, apart from the Fueling Station change you pointed out, everything else is just because of the way they are made in this modpack.

Performing a quick test, then I will review.

2023-12-20 23:42 UTC, IntegerLimit requested changes

2023-12-20 23:42 UTC, IntegerLimit commented on overrides/resources/questbook/lang/zh_cn.lang
Can we remove bilingual translations for now? I still want to have a bit of a discussion and a way to automatically update the english version first.

2023-12-21 04:43 UTC, IntegerLimit requested changes

2023-12-21 04:43 UTC, IntegerLimit commented on overrides/resources/enderio/lang/en_us.lang
> +enderio.item_endergy_conduit_electron=Lumium Energy Conduit
Maybe try `enderio.item_endergy_conduit_electrum`?

2023-12-21 04:43 UTC, IntegerLimit commented
Just one problem, and one requested change.

2023-12-21 04:47 UTC, IntegerLimit commented on overrides/resources/enderio/lang/en_us.lang
> +enderio.item_endergy_conduit_electron=Lumium Energy Conduit
That change worked for me. Please apply it for both `en_us` and `zh_cn` lang files.

2023-12-21 15:24 UTC, zero6six commented on overrides/resources/questbook/lang/zh_cn.lang
Sorry, that was a accident, I copied wrong file in my repo. I will change the directory structure of my own repository to avoid this problem in the future.

2023-12-21 15:25 UTC, zero6six commented on overrides/resources/enderio/lang/en_us.lang
> +enderio.item_endergy_conduit_electron=Lumium Energy Conduit
It should be `enderio.item_endergy_conduit_electrum.name`, I'm sorry for that.

2023-12-21 15:57 UTC, zero6six commented
Thanks to @Ede1weiss3181, I also uploaded translations for expert QB beyond finishing requested changes.

2023-12-22 01:34 UTC, IntegerLimit commented on overrides/resources/questbook/lang/zh_cn.lang
All Good!

2023-12-22 01:46 UTC, IntegerLimit commented on overrides/resources/enderio/lang/en_us.lang
> +enderio.item_endergy_conduit_electron=Lumium Energy Conduit
I've changed it from `enderio.item_endergy_conduit_electron.name` to `enderio.item_endergy_conduit_electrum.name` in my latest two commits. Probably just an oversight.

2023-12-22 01:56 UTC, IntegerLimit approved these changes

2023-12-22 02:03 UTC, merged