Dye fixes and improvements
Nomi-CEu/Nomi-CEu pull request #628
Opened 2024-02-23 20:15 UTC by ProTriforcer

- When you show uses for lapis, bonemeal, cocoa or ink sacs, you won't see 41 JEI pages of recipes making things blue, unless you craft them into a dye first. Inspired by 1.14 dyes.
This breaks some autocrafts, like concrete and other dyed things, but imo reducing JEI clutter is worth it
- Change elevator and slime block redyeing recipes to use dye oredicts instead of just vanilla items 
- Add the "dye" tag to all dyes to fix satchel redyeing

2024-02-29 22:08 UTC, IntegerLimit commented
@tracer4b LGTM. Can you test it in game, and check balancing, etc.

Also, what do you think of this change?

2024-03-10 07:26 UTC, tracer4b requested changes

2024-03-10 07:26 UTC, tracer4b commented on overrides/scripts/undyeing.zs
> +recipes.addShapeless(<metaitem:dye.blue>, [<minecraft:dye:4>]);
Should add conversions for lazurite, sodalite, and metal mixture dust to their respective dyes as well

2024-03-10 08:16 UTC, ProTriforcer commented
That should be all of them. Disregard the crushe _dYe_ llowLimonite
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/25221392/d669d4f0-79f6-4285-8c4d-c94f72a84e4b)

2024-03-10 08:35 UTC, IntegerLimit approved these changes

2024-03-10 08:39 UTC, tracer4b approved these changes

2024-03-10 08:45 UTC, merged

2024-07-23 06:37 UTC, Testure commented
Please stop existing

2024-07-23 10:39 UTC, IntegerLimit commented
As in... revert the PR, or?

2024-07-23 22:39 UTC, Testure commented
Yes, revert back to sanity

2024-07-23 22:46 UTC, eutro commented
Gregtech players when they need to perform one (1) additional craft to dye things in exchange for JEI no longer being incomprehensible for items that happen to be usable for dye.

2024-07-24 03:46 UTC, IntegerLimit commented
No, we will not return to insanity. You shall perform the craft!