Update NAE2 to 1.6.4 and set a custom recipe for 256k+ storage cells.
Nomi-CEu/Nomi-CEu pull request #791
Opened 2024-07-11 03:15 UTC by GavinFF-SS

Changes I think will make the pack better.

2024-07-11 08:29 UTC, IntegerLimit commented
256k Recipes already exist... see https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/nae2.groovy.

Once that script is deleted, apart from that, looks good!

2024-07-11 19:01 UTC, GavinFF-SS commented
yeah i probably shouldn't have merged nomi ceu main branch into my fork when this pull request isn't merged, mistake on my part, hopefully it doesn't mess up too much (if anything at all), sorry about that.

2024-07-11 23:26 UTC, IntegerLimit requested changes

2024-07-11 23:26 UTC, IntegerLimit commented on overrides/scripts/NAE2.zs
One change: Please delete this script file (as per my comment above about it being implemented in groovy).

Otherwise, this PR looks good!

2024-07-11 23:52 UTC, GavinFF-SS commented on overrides/scripts/NAE2.zs
alright, done

2024-07-12 00:04 UTC, IntegerLimit approved these changes
Just a final check: Does NAE2 1.6.4 work with our current version of AE2 (.56.4)? Or does it require .56.5?

2024-07-12 00:20 UTC, GavinFF-SS commented
It uses AE2UEL .56.5 if I remember correctly.

2024-07-12 00:28 UTC, IntegerLimit commented
Alright, then I'll merge this after I merge https://github.com/Nomi-CEu/Nomi-CEu/pull/793.

2024-07-12 06:16 UTC, merged