Replace small piles from Rare Earth centrifuging with large piles
Nomi-CEu/Nomi-CEu pull request #809
Opened 2024-07-18 11:06 UTC by ProTriforcer

2024-07-18 11:55 UTC, IntegerLimit requested changes

2024-07-18 11:55 UTC, IntegerLimit commented on overrides/groovy/postInit/Post-Initial/Main/General/Mid-Game/midgame.groovy
Three Comments:

Replace `
// Replace small piles from Rare Earth centrifuging with large piles` with `// Make Rare Earth Centrifuging Output Full Dusts`

Replace `mods.gregtech.centrifuge.removeByInput(20, [metaitem('dustRareEarth')], null)` with `mods.gregtech.centrifuge.removeByInput([metaitem('dustRareEarth')], null)` (Custom Labs Helper)

Add `import static gregtech.api.GTValues.*` at the top of the file, (below the other import, with empty one line separating them), and replace `.EUt(20)` with `.EUt(VA[LV])` (30 EUt, not exact, but close enough and doesn't use magic numbers)

Otherwise looks like a good change!

2024-07-18 12:01 UTC, IntegerLimit commented
Just checking, have you made sure the script runs properly in-game?

2024-07-18 12:11 UTC, ProTriforcer commented
Now i have. It works

2024-07-19 01:11 UTC, IntegerLimit approved these changes

2024-07-19 01:11 UTC, merged